{% set name = "jc" %}
{% set version = "1.25.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jc-{{ version }}.tar.gz
  sha256: f8ac0e4bc427b0ee8a3bdb07a254cc9df6b6036cd440f6c425e2e519cdbda78a

build:
  entry_points:
    - jc=jc.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pygments >=2.3.0
    - python >={{ python_min }}
    - xmltodict >=0.12.0
    - ruamel.yaml >=0.15.0

test:
  imports:
    - jc
  commands:
    - pip check
    - jc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kellyjonbrazil/jc
  doc_url: https://github.com/kellyjonbrazil/jc/tree/master/docs
  summary: Converts the output of popular command-line tools and file-types to JSON.
  license: MIT
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
