{% set name = "jc" %}
{% set version = "1.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jc-{{ version }}.tar.gz
  sha256: de4a6399f265cf9250f0883d415ab5c5a081d165ead80c38a27da68fe71a4563

build:
  entry_points:
    - jc=jc.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments >=2.3.0
    - python >=3.6
    - ruamel.yaml >=0.15.0
    - xmltodict >=0.12.0

test:
  imports:
    - jc
  commands:
    - pip check
    - jc --help
  requires:
    - pip

about:
  home: https://github.com/kellyjonbrazil/jc
  doc_url: https://github.com/kellyjonbrazil/jc/tree/master/docs
  summary: Converts the output of popular command-line tools and file-types to JSON.
  license: MIT
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
