{% set name = "jc" %}
{% set version = "1.25.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jc-{{ version }}.tar.gz
  sha256: 97ada193495f79550f06fe0cbfb119ff470bcca57c1cc593a5cdb0008720e0b3

build:
  entry_points:
    - jc=jc.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pygments >=2.3.0
    - python >=3.7
    - xmltodict >=0.12.0

    # needs this but not listed
    - ruamel.yaml

test:
  imports:
    - jc
  commands:
    - pip check
    - jc --help
  requires:
    - pip

about:
  home: https://github.com/kellyjonbrazil/jc
  doc_url: https://github.com/kellyjonbrazil/jc/tree/master/docs
  summary: Converts the output of popular command-line tools and file-types to JSON.
  license: MIT
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
