{% set name = "jc" %}
{% set version = "1.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jc-{{ version }}.tar.gz
  sha256: 57d6e5d6ded87b2fcc08be715a3aed326e930cb5c9d7abcc9e4d57fa8229189a

build:
  entry_points:
    - jc=jc.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments >=2.3.0
    - python >=3.6
    - ruamel.yaml >=0.15.0
    - xmltodict >=0.12.0

test:
  imports:
    - jc
  commands:
    - pip check
    - jc --help
  requires:
    - pip

about:
  home: https://github.com/kellyjonbrazil/jc
  doc_url: https://github.com/kellyjonbrazil/jc/tree/master/docs
  summary: Converts the output of popular command-line tools and file-types to JSON.
  license: MIT
  license_file:
    - LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
