schema_version: 1

context:
  name: jc
  version: "1.26.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jc-${{ version }}.tar.gz
  sha256: 576b5615b5677c7bf4aacf97dcc6c6b4bf437bbc420c7db77b43ae1785372c9e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - jc=jc.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - ruamel.yaml >=0.15.0
    - xmltodict >=0.12.0
    - pygments >=2.3.0

tests:
  - python:
      imports:
        - jc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - jc --help

about:
  summary: Converts the output of popular command-line tools and file-types to JSON.
  license: MIT
  license_file:
    - LICENSE.md
  homepage: https://github.com/kellyjonbrazil/jc
  documentation: https://github.com/kellyjonbrazil/jc/tree/master/docs

extra:
  recipe-maintainers:
    - thewchan
