schema_version: 1

context:
  name: jc
  version: "1.25.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jc-${{ version }}.tar.gz
  sha256: 63481e34d92715781e1b094eca7d76d122a14489463d45b7f3e8180f44ea3a10

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - jc=jc.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - pygments >=2.3.0
    - python >=${{ python_min }}
    - xmltodict >=0.12.0
    - ruamel.yaml >=0.15.0

tests:
  - python:
      imports:
        - jc
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - jc --help

about:
  summary: Converts the output of popular command-line tools and file-types to JSON.
  license: MIT
  license_file:
    - LICENSE.md
  homepage: https://github.com/kellyjonbrazil/jc
  documentation: https://github.com/kellyjonbrazil/jc/tree/master/docs

extra:
  recipe-maintainers:
    - thewchan
